Adjective = [
    "Angry",
    "Blissful",
    "Brave",
    "Bright",
    "Comfortable",
    "Courageous",
    "Emerald",
    "Fair",
    "Gray",
    "Pale",
    "Fiery",
    "Goodly",
    "Happy",
    "Home of the",
    "Laughing",
    "Lonesome",
    "Lovely",
    "Massacred",
    "Motley",
    "Pious",
    "Purple",
    "Sad",
    "Sign of the",
    "Simple",
    "Sorrowful",
    "Stalwart",
    "Stately",
    "Weary",
    "Whisky",
    "Whispering",
    "Silly",
    "Adventuring"
]
Root = [
    "Maiden",
    "Gnome",
    "Master",
    "Warrior",
    "Jug",
    "Glass",
    "Brewery",
    "Inn",
    "Hostelry",
    "Tavern",
    "Hero",
    "Castle",
    "Dragon",
    "Unicorn",
    "Pony",
    "Cup",
    "Plate",
    "Beard",
    "Sword",
    "Bow",
    "Axe",
    "Devil",
    "Blackguard",
    "Giant",
    "Fiend",
    "Shield",
    "Tankard",
    "Ranger",
    "Cloud",
    "Fisher",
    "God",
    "Elf",
    "Dwarf",
    "Orc",
    "Bed",
    "Bear",
    "Lion",
    "Moose",
    "Gargoyle"
]
Gender = [
    "Male",
    "Female"
]
Race = [
    "human",
    "elf",
    "tiefling",
    "gnome",
    "halfling",
    "dwarf",
    "half-orc",
    "half-ogre",
    "half-elf"
]
Level = [
    "1st-level",
    "2nd-level",
    "3rd-level",
    "4th-level",
    "5th-level",
    "6th-level",
    "7th-level",
    "8th-level",
    "9th-level",
    "10th-level"
]
Class = [
    "NPC commoner",
    "fighter",
    "ranger",
    "cleric",
    "barbarian",
    "rogue",
    "bard",
    "sorcerer",
    "NPC warrior",
    "NPC aristocrat"
]
Clientele = [
    "a bard performing for drinks",
    "a bewildered barbarian",
    "a couple on a date",
    "a few anonymous drunks",
    "a fighter looking for trouble",
    "a group of dicing rogues",
    "a group of elves sipping wine",
    "a press-gang collecting drunks",
    "a ranger looking for her wolf",
    "a rogue secretly emptying purses",
    "a snobby aristocrat",
    "a sorcerer selling spells",
    "a wizard deep in his cups",
    "adventurers planing their next move",
    "an assassin secretly biding his time",
    "carnies out on the town",
    "cleric of Pelor preaching in corner",
    "cloaked figure in corner",
    "company of drunken adventurers",
    "company of stalwart adventurers",
    "dwarf buying rounds for the house",
    "gang of half-orc street toughs",
    "grim paladins on crusade",
    "group of singing halflings",
    "guardsmen on a stake-out",
    "halfling tourists",
    "humans gnawing turkey legs",
    "party of rowdy dwarves",
    "soft-spoken traveling monks",
    "town guard captain having a meal",
    "youngsters on a lark"
]
Clientele1 = [
    "A bard performing for drinks",
    "A bewildered barbarian",
    "A couple on a date",
    "A few anonymous drunks",
    "A fighter looking for trouble",
    "A group of dicing rogues",
    "A group of elves sipping wine",
    "A press-gang collecting drunks",
    "A ranger looking for her wolf",
    "A rogue secretly emptying purses",
    "A snobby aristocrat",
    "A sorcerer selling spells",
    "A wizard deep in his cups",
    "Adventurers planing their next move",
    "An assassin secretly biding his time",
    "Carnies out on the town",
    "Cleric of Pelor preaching in corner",
    "Cloaked figure in corner",
    "Company of drunken adventurers",
    "Company of stalwart adventurers",
    "Dwarf buying rounds for the house",
    "Gang of half-orc street toughs",
    "Grim paladins on crusade",
    "Group of singing halflings",
    "Guardsmen on a stake-out",
    "Halfling tourists",
    "Humans gnawing turkey legs",
    "Party of rowdy dwarves",
    "Soft-spoken traveling monks",
    "Town guard captain having a meal",
    "Youngsters on a lark"
]
Rumors = [
    "Thieves have stolen the crown jewels.",
    "A dragon has flown into a town and demanded tribute.",
    "The tomb of an old wizard has been discovered.",
    "Wealthy merchants are being killed in their homes.",
    "The statue in the town square was found to be a petrified paladin.",
    "A caravan of important goods is about to leave for a trip through a dangerous area.",
    "Cultists are kidnapping potential sacrifices.",
    "Goblins riding spider eaters have been attacking the outskirts of a town.",
    "Local bandits have joined forces with a tribe of bugbears.",
    "A blackguard is organizing monsters in an area.",
    "A gate to the Lower Planes threatens to bring more demons to the world.",
    "Miners have accidentally released something awful that once was buried deep.",
    "A wizard’s guild challenges the ruling council.",
    "Racial tensions between humans and elves are rising.",
    "A mysterious fog has brought ghosts into town.",
    "The holy symbol of a high priest is missing.",
    "An evil wizard has developed a new type of golem.",
    "Someone in town is a werewolf.",
    "Slavers continue to raid a local community.",
    "A fire elemental has escaped from a wizard’s lab.",
    "Bugbears are demanding a toll on a well-traveled bridge.",
    "A mirror of opposition has created an evil duplicate of a hero.",
    "Two orc tribes wage a bloody war.",
    "New construction reveals a previously unknown underground tomb.",
    "A nearby kingdom has launched an invasion.",
    "Two well-known heroes will soon fight a duel.",
    "An ancient sword must be recovered to defeat a ravaging -monster.",
    "A prophecy foretells of coming doom unless an artifact is -recovered.",
    "Ogres have kidnaped the mayor’s daughter.",
    "A wizard is buried in a trap-filled tomb with her powerful magic items.",
    "An enchanter is compelling others to steal for him.",
    "A shapechanged mind flayer is gathering mentally controlled servitors.",
    "A plague brought by wererats threatens a community.",
    "The keys to disarming all the magic traps in a wizard’s tower have gone missing.",
    "Sahuagin are being driven out of the sea to attack coastal -villages.",
    "Gravediggers have discovered a huge, ghoul-filled catacomb under the cemetery.",
    "A wizard needs a particularly rare spell component found only in the deep jungle.",
    "A map showing the location of an ancient magic forge is discovered.",
    "Various monsters have long preyed upon people from within the sewers of a major city.",
    "An emissary going into a hostile kingdom needs an escort.",
    "Vampires are preying upon a small town.",
    "A haunted tower is reputed to be filled with treasure.",
    "Barbarians have torn up a village in a violent rage.",
    "Giants are stealing cattle from local farmers.",
    "Unexplained snowstorms have brought winter wolves into an otherwise peaceful area.",
    "A lonely mountain pass is guarded by a powerful sphinx denying all passage.",
    "Evil mercenaries are constructing a fortress not far from the community.",
    "An antidote to a magic poison must be found before the duke dies.",
    "A druid needs help defending her grove against goblins.",
    "An ancient curse is turning innocent people into evil murderers.",
    "Gargoyles are killing giant eagles in the mountains.",
    "Mysterious merchants sell faulty magic items in town and then attempt to slink away.",
    "A recently recovered artifact causes arcane spellcasters’ powers to go awry.",
    "An evil noble has put a price on a good noble’s head.",
    "Adventurers exploring a dungeon have not returned in a week.",
    "The funeral for a good fighter was disrupted by enemies he made while alive.",
    "Colossal vermin are straying out of the desert to attack settlements.",
    "An evil tyrant has outlawed unsanctioned magic use.",
    "A huge dire wolf, apparently immune to magic, is organizing the wolves in the wood.",
    "A community of gnomes has built a flying ship.",
    "An island at the center of the lake is actually the top of a strange, submerged fortress.",
    "Buried below the Tree of the World lies the Master Clock of Time.",
    "A child has wandered into a vast necropolis, and dusk approaches quickly.",
    "All the dwarves in an underground city have disappeared.",
    "A strange green smoke billows out of a cave near a mysterious ruin.",
    "Mysterious groaning sounds come from a haunted wood at night.",
    "Thieves steal a great treasure and flee into Mordenkainen’s magnificent mansion.",
    "A sorcerer attempted to travel ethereally but disappeared completely in the process.",
    "A paladin’s quest for atonement led her to a troll lair too well-defended for her to tackle alone.",
    "A kingdom known for its wizards prepares for war.",
    "The high priest is an illusion.",
    "A new noble seeks to clear a patch of wilderness of all monsters.",
    "A bulette is tearing apart viable farmland.",
    "A infestation of stirges drives yuan-ti closer to civilized lands.",
    "Treants in the woods are threatened by a huge fire of mysterious origin.",
    "Clerics who have resurrected a long-dead hero discovered she’s not what they thought.",
    "A sorrowful bard tells a tavern tale of his imprisoned companions.",
    "Evil nobles have created an adventurers’ guild to monitor and control adventurers.",
    "A halfling caravan must pass through an ankheg-infested wilderness.",
    "All the doors in the king’s castle are suddenly arcane locked and fire trapped.",
    "An innocent man, about to be hanged, pleads for someone to help him.",
    "The tomb of a powerful wizard, filled with magic items, has sunk into the swamp.",
    "Someone is sabotaging wagons and carts to come apart when they travel at high speed.",
    "A certain type of frogs, found only in an isolated valley, fall like rain on a major city.",
    "A jealous rival threatens to stop a well-attended wedding.",
    "A woman who mysteriously vanished years ago has been seen walking on the surface of a lake.",
    "An earthquake has uncovered a previously unknown dungeon.",
    "A wronged half-elf needs a champion to fight for her in a gladiatorial trial.",
    "At the eye of the storm that tears across the land lies a floating citadel.",
    "People grow suspicious of half-orc merchants peddling gold dragon parts in the market.",
    "An absentminded wizard has let her rod of wonder fall into the wrong hands.",
    "Undead shadows vex a large library, especially an old storeroom long left undisturbed.",
    "The door into an abandoned house in the middle of town is in fact a magic portal.",
    "Barge pirates have made a deal with a covey of hags and exact a high toll to use the river.",
    "Two parts of a magic item are in the hands of bitter enemies; the third piece is lost.",
    "A clutch of wyverns is preying upon sheep as well as shepherds.",
    "Evil clerics gather in secret to summon a monstrous god to the world.",
    "A major city faces a siege by a force of humans, duergar, and gnolls.",
    "A huge gemstone supposedly lies within an ancient ruined monastery.",
    "Lizardfolk riding dragon turtles sell their services as mercenaries to the highest bidder."
]
Accommodations = [
    "Poor (a place on the floor near the hearth and a flea-ridden blanket amongst the riff-raff) for 1 sp/day",
    "Common (a placed on a raised, heated floor, blanket and pillow, amongst higher-class company) for 3 sp/day",
    "Good (a small private room with one bed, some amenities and a covered chamber pot) for 5 sp/day",
    "Noble (a large private room with large bed, private bath with hot water on request, snacks on request, and private chamber pot in a separate chamber) for 1 gp/day"
]
Submenu13A = [
    "Bacon",
    "Ham",
    "Beef steak",
    "Kippers",
    "Smoked sausage",
    "Blood pudding",
    "Fried perch",
    "Hash",
    "Meatballs",
    "1A"
]
Submenu13B = [
    "Pork chop",
    "Chicken half",
    "Leg of mutton",
    "Rabbit stew",
    "Sausage",
    "Veal sweetbreads",
    "Lamb stew",
    "1A"
]
Submenu13C = [
    "Beef steak",
    "Whole duck",
    "Pork liver",
    "Mixed grill",
    "Stuffed trout",
    "Lamb chop",
    "Broiled catfish",
    "1A"
]
Submenu1A = [
    "Dog stew",
    "Cat cutlet",
    "Frog legs",
    "Octopus",
    "Wyvern shank",
    "Monkey brain",
    "Triceratops steak",
    "Basilisk tail",
    "Bulette fin",
    "Darkmantle",
    "Eagle breast",
    "Owlbear chop",
    "Wild boar headcheese",
    "Giant toad tongue",
    "Shark filet"
]
Menu14 = [
    "Chicken eggs",
    "Duck eggs",
    "Goose eggs",
    "Sharp cheese",
    "Soft cheese",
    "Curds",
    "14A"
]
Submenu14A = [
    "Hippogriff egg",
    "Griffin-milk cheese",
    "Gnomes’ yogurt",
    "Deep dwarven blue cheese",
    "Dragon turtle omelet",
    "Quail eggs"
]
Menu15 = [
    "Carrots",
    "Turnips",
    "Potato",
    "Taro",
    "Yams",
    "Onions",
    "Cabbage",
    "Leeks",
    "Collard greens",
    "Broccoli",
    "Spinach",
    "Corn",
    "Chick peas",
    "Peas",
    "Succotash",
    "Green beans",
    "Lentils",
    "Broad beans",
    "Black beans",
    "15A"
]
Submenu15A = [
    "Udoroot frond",
    "Giant bean",
    "Assassin vine leaf",
    "Shrieker steak",
    "Pumpkin",
    "Okra",
    "Seaweed",
    "Artichoke"
]
Menu16 = [
    "Apple",
    "Pear",
    "Peach",
    "Dates",
    "Strawberries",
    "Raspberries",
    "Blackberries",
    "Blueberries",
    "Currants",
    "Raisins",
    "Melon",
    "Stewed prunes",
    "16A"
]
Submenu16A = [
    "Assassin vine berries",
    "Coconut",
    "Pomegranite",
    "Banana",
    "Guava",
    "Black apple",
    "Underdark glowfruit",
    "Sea-grapes",
    "Breadfruit"
]
Menu17 = [
    "Coarse rye bread",
    "Nut bread",
    "Rice",
    "Millet",
    "Flatbread",
    "Corn pone",
    "Mush",
    "Oatmeal",
    "17A"
]
Submenu17A = [
    "Wild rice",
    "Sunflower loaf",
    "Goblin bannock",
    "Centaur rye",
    "Sea oats",
    "Tahini",
    "Pine nuts",
    "Marzipan"
]
Menu18 = [
    "Berry pie",
    "Apple pie",
    "Raisin pie",
    "Pecan pie",
    "Mince pie",
    "Rhubarb pie",
    "Plain cake",
    "Walnut cake",
    "Fruitcake",
    "Spice bread",
    "Custard",
    "Plum pudding",
    "Rice pudding",
    "Applesauce",
    "18A"
]
Submenu18A = [
    "Wood-elven crisp cakes",
    "Crème brulée",
    "Sherbet",
    "Honey-cake",
    "Spiced, stuffed pumpkin",
    "Chocolate torte",
    "Toffee",
    "Vanilla fudge"
]
MealCost = [
    1,
    2,
    4,
    8
]
ExoticCost = [
    0,
    2,
    4,
    6
]
CostSuffix = [
"sp",
"sp",
"sp",
"sp"
]
ExoticChance = [
0,
5,
15,
35]